pipeline:
  class_path: speed.pipeline_challenge.PretrainPipeline
  init_args:
    do_ica: False
    line_freqs: [60]
    sfreq: 100
    hp_freq: 0.5
    lp_freq: 50
    window_length: 30
    shift_seconds: # None
    metrics_path: "/data/linsk/hbn_preprocessed/logs/quality_metrics.csv"
    return_quality_metrics: True
    drop_bad_quality: True
    channels_to_remove: 
    channels: ['Fp1', 'Fp2', 'F7', 'F3', 'Fz', 'F4', 'F8', 'T7', 'C3', 'Cz', 'C4', 'T8', 'T5', 'P3', 'Pz', 'P4', 'T6', 'O1', 'O2']
dataset_path: "/data/agjma/HBN_EEG_Raw/"
out_path: "/data/linsk/hbn_preprocessed"
log_path: "/data/linsk/hbn_preprocessed/logs/hbn_log.txt"
file_extension: ".edf" # RestingState_eeg - run ALL HBN
overwrite: False
shuffle_files: True
batch_size: 2
n_jobs: 1
save_as_hdf5: True 
# nohup python scripts/preprocess_hbn.py --config configs/tuh_30s.yaml > /data/linsk/hbn_preprocessed/logs/nohup.out 2>&1 &
